/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sociograph
 */
public class Ventana_Texto extends javax.swing.JFrame {
    
    private String ruta_word;
    private String ruta_fichero;

    /**
     * Creates new form Ventana_Texto
     */
    public Ventana_Texto(String ruta_word) {
        initComponents();
        this.ruta_word=ruta_word;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrirDocx = new javax.swing.JButton();
        lblNombreDocx = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAbrirDocx.setText("Abrir en Word");
        btnAbrirDocx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirDocxActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrirDocx, java.awt.BorderLayout.PAGE_END);

        lblNombreDocx.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(lblNombreDocx, java.awt.BorderLayout.PAGE_START);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirDocxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirDocxActionPerformed
        try {
            // TODO add your handling code here:
            Runtime runTime = Runtime.getRuntime();
            Process process = runTime.exec(ruta_word+"\\"+ruta_fichero);
        } catch (IOException ex) {
            Logger.getLogger(Ventana_Texto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAbrirDocxActionPerformed


    public void setTexto(String text) {
        textArea.setText(text);
    }
    
    public void setNombre(String name){
        lblNombreDocx.setText(name);
    }
    
    public void setButton(String ruta){
        this.ruta_fichero=ruta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirDocx;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreDocx;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
